version: '3'
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
  api:
    container_name: api-container
    build: node12
    working_dir:
    image: clean-node-api
    restart: always
    command: npm run debug
    volume:
      - ./dist:/usr/src/clean-node-api/dist/
      - ./package.json:/usr/src/clean-node-api/dist/package.json

    ports:
      - '3000:3000'
      - '9222:9222'
    links:
      - mongo
